---
name: Terraform

on:
  workflow_call:
    inputs:
      aws_bucket:
        type: string
        required: true
      aws_endpoint_url_s3:
        type: string
        required: true
      gh_tf_owner:
        type: string
        required: true
      gh_tf_app_id:
        type: string
        required: true
      gh_tf_app_installation_id:
        type: string
        required: true
      path:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      gh_tf_app_pem_file:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

env:
  # S3 backend configuration
  AWS_BUCKET: ${{ inputs.aws_bucket }}
  AWS_ENDPOINT_URL_S3: ${{ inputs.aws_endpoint_url_s3 }}
  # GitHub App configuration
  GITHUB_OWNER: ${{ inputs.gh_tf_owner }}
  GITHUB_APP_ID: ${{ inputs.gh_tf_app_id }}
  GITHUB_APP_INSTALLATION_ID: ${{ inputs.gh_tf_app_installation_id }}
  # Terraform configuration
  TF_WORKSPACE: ${{ inputs.gh_tf_owner }}
  TF_VAR_config: ../config/${{ inputs.path }}
  TF_IN_AUTOMATION: true

defaults:
  run:
    shell: bash

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the called repository
        uses: actions/checkout@v7
        with:
          repository: bruzit/github-organization-as-code
          ref: ${{ job.workflow_sha }}
          persist-credentials: false
      - name: Checkout the caller repository
        uses: actions/checkout@v7
        with:
          path: config
          sparse-checkout: ${{ inputs.path }}
          sparse-checkout-cone-mode: false
          persist-credentials: false
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
      - name: Terraform fmt
        run: terraform -chdir=terraform fmt -check
      - name: Terraform init
        id: init
        run: terraform -chdir=terraform init -input=false -backend-config="bucket=$AWS_BUCKET"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
      - name: Terraform validate
        run: terraform -chdir=terraform validate
        env:
          GITHUB_APP_PEM_FILE: |
            ${{ secrets.gh_tf_app_pem_file }}
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          GITHUB_APP_PEM_FILE: |
            ${{ secrets.gh_tf_app_pem_file }}
